[tox]
requires =
    tox>=4
env_list = py{310,311,312,313}

[testenv]
description = Run test suite using different Python versions
deps =
    pytest>=9
    pytest-asyncio>=1.4
    pytest-sugar
    pytest-cov
    httpx>=0.28
commands =
    pytest --cov=discogs_alert --cov-report=term-missing --cov-fail-under=88 {posargs:tests}
