[tox]
requires =
    tox>=4
env_list = py{310,311,312,313}

[testenv]
description = Run test suite using different Python versions
deps =
    pytest>=7
    pytest-sugar
    pytest-cov
commands =
    pytest --cov=discogs_alert --cov-report=term-missing --cov-fail-under=80 {posargs:tests}
