name: check-my-prs
on: [pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest  # [macos-latest, windows-latest]
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "pypy-3.9"]
    name: "Ruff style (Python ${{ matrix.python-version }})"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip3 install ruff
      - run: ruff check discogs_alert

  lfs-warning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actionsdesk/lfs-warning@v3.2
        with:
          filesizelimit: 1MB
