name: check-my-prs
on: [pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    name: "ruff (Python ${{ matrix.python-version }})"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip3 install ruff
      - run: ruff check discogs_alert tests

  tox:
    runs-on: ubuntu-latest
    name: "tox"
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip3 install tox
      - run: tox -e py$(echo ${{ matrix.python-version }} | tr -d .)

  lfs-warning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actionsdesk/lfs-warning@v3.2
        with:
          filesizelimit: 1MB
